version: 2
updates:
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: daily
      time: "11:05"
      timezone: Europe/Prague
    pull-request-branch-name:
      separator: "-"
    commit-message:
      prefix: chore
