name: Release

on:
  workflow_dispatch:
  # push:
  #   branches:
  #     - main

env:
  CI: true
  PNPM_CACHE_FOLDER: .pnpm-store
jobs:
  release:
    timeout-minutes: 15
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install pnpm
        run: npm i pnpm@9 -g

      - name: Setup pnpm cache directory
        run: pnpm config set store-dir $PNPM_CACHE_FOLDER

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Publish packages
        working-directory: .
        run: |
          npm config set //npm.pkg.github.com/:_authToken=${GITHUB_TOKEN}
          CWD=`pwd`

          cd $CWD/packages/eslint/eslint-config-base && npm ${{ env.PUBLISH_COMMAND }}
          cd $CWD/packages/eslint/eslint-config-node && npm ${{ env.PUBLISH_COMMAND }}
          cd $CWD/packages/eslint/eslint-config-prettier && npm ${{ env.PUBLISH_COMMAND }}
          cd $CWD/packages/eslint/eslint-config-typescript && npm ${{ env.PUBLISH_COMMAND }}
          cd $CWD/packages/prettier/prettier-config && npm ${{ env.PUBLISH_COMMAND }}
          cd $CWD
        env:
          PUBLISH_COMMAND: ${{ contains(github.ref, 'beta') && 'publish --tag beta' || 'publish' }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
